; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = serial
src_dir = .

[env:serial]
platform = espressif32
board = nologo_esp32c3_super_mini
framework = arduino
lib_deps = 
    https://github.com/bertrik/minishell
    senseshift/Serial_BLE
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

